---
version: "3"
services:
  coturn:
    image: docker.io/coturn/coturn
    container_name: coturn
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf:ro
      - /etc/ssl/private/coturn-privkey.pem:/etc/ssl/private/privkey.pem:ro
      - /etc/ssl/certs/coturn-cert.pem:/etc/ssl/certs/cert.pem:ro
    ports:
      ## STUN/TURN
      - "3478:3478"
      - "3478:3478/udp"
      - "3479:3479"
      - "3479:3479/udp"
      - "80:80"
      - "80:80/udp"
      ## STUN/TURN SSL
      - "443:443"
      - "443:443/udp"
      # Relay Ports for TURN
      - "32769-65535:32769-65535/udp"
    logging:
      driver: "journald"
